# Generated by Django 3.1.3 on 2020-11-23 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.TextField(max_length=50, verbose_name='Schema name')),
                ('column_separator', models.CharField(choices=[('COMMA', 'Comma(,)'), ('DOT', 'Dot(.)')], default='COMMA', max_length=5)),
                ('string_character', models.CharField(choices=[('ONE_QUOTE', "One-quote(')"), ('DOUBLE_QUOTE', 'Double-quote(")')], default='DOUBLE_QUOTE', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(help_text='Name', max_length=250, verbose_name='First name')),
                ('last_name', models.TextField(help_text='Name', max_length=250, verbose_name='Last name')),
                ('job', models.CharField(help_text='Job role', max_length=250, verbose_name='Job')),
                ('email', models.EmailField(help_text='Email', max_length=254, verbose_name='Email')),
                ('domain_name', models.CharField(help_text='Domain', max_length=10, verbose_name='Domain')),
                ('phone_number', models.CharField(help_text='Phone number', max_length=15, verbose_name='Phone')),
                ('company_name', models.CharField(help_text='Company', max_length=250, verbose_name='Company')),
                ('text', models.TextField()),
                ('integer', models.IntegerField(default=18, validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(60)])),
                ('address', models.CharField(help_text='Address', max_length=250, verbose_name='Address')),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='schemacolumns',
            index=models.Index(fields=['first_name', 'last_name'], name='schema_sche_first_n_cea8f5_idx'),
        ),
    ]
