# Generated by Django 3.1.3 on 2020-11-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0002_auto_20201123_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschema',
            name='schema_name',
            field=models.CharField(max_length=100, verbose_name='Schema name'),
        ),
        migrations.AlterField(
            model_name='schemacolumns',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='schemacolumns',
            name='column_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schemacolumns',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='schemacolumns',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schemacolumns',
            name='domain_name',
            field=models.CharField(max_length=10, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='schemacolumns',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='schemacolumns',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='schemacolumns',
            name='job',
            field=models.CharField(max_length=50, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='schemacolumns',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='schemacolumns',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone'),
        ),
    ]
