# Generated by Django 3.1.3 on 2020-11-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0003_auto_20201123_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemacolumns',
            name='type',
            field=models.CharField(choices=[('JOB', 'Job'), ('EMAIL', 'Email')], max_length=12, null=True),
        ),
    ]
