# Generated by Django 3.1.3 on 2020-11-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0004_schemacolumns_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchemaColumns',
            new_name='SchemaColumn',
        ),
        migrations.RemoveIndex(
            model_name='schemacolumn',
            name='schema_sche_first_n_cea8f5_idx',
        ),
        migrations.AddIndex(
            model_name='schemacolumn',
            index=models.Index(fields=['first_name', 'last_name'], name='schema_sche_first_n_e2e2cb_idx'),
        ),
    ]
