# Generated by Django 3.1.3 on 2020-11-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0005_auto_20201123_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemacolumn',
            name='type',
        ),
    ]
