# Generated by Django 3.1.3 on 2021-01-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0006_remove_schemacolumn_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemacolumn',
            name='rate_type',
            field=models.CharField(choices=[(models.CharField(max_length=150, verbose_name='Address'), 'ADDRESS'), (models.DateField(auto_now=True), 'DATE')], max_length=20, null=True),
        ),
    ]
