# Generated by Django 3.1.3 on 2021-01-24 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0007_schemacolumn_rate_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemacolumn',
            name='id',
        ),
        migrations.RemoveField(
            model_name='schemacolumn',
            name='rate_type',
        ),
        migrations.AddField(
            model_name='schemacolumn',
            name='order',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schemacolumn',
            name='type',
            field=models.CharField(choices=[(models.CharField(max_length=50, verbose_name='Job'), 'Job'), (models.EmailField(max_length=254, verbose_name='Email'), 'Email'), (models.CharField(max_length=10, verbose_name='Domain'), 'Domain Name'), (models.CharField(max_length=15, verbose_name='Phone'), 'Phone Number'), (models.CharField(max_length=100, verbose_name='Company'), 'Company Name'), (models.IntegerField(default=18, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(18)]), 'Age'), (models.CharField(max_length=150, verbose_name='Address'), 'Address'), (models.DateField(auto_now_add=True), 'Date')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
