# Generated by Django 3.1.3 on 2021-01-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0008_auto_20210124_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemacolumn',
            name='order',
        ),
        migrations.AddField(
            model_name='schemacolumn',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
